## Programming Assignment 2: Caching the Inverse of a Matrix
## The functions below create a special object that stores a matrix and chaches its inverse.

## Specifically, 
## makeCacheMatrix is the function that creates a special "matrix" object that can cache its inverse.
## set_matrix sets the matrix value
## get_matrix gets the matrix value
## set_matrixInv sets/caches the inverse of a matrix
## get_matrixInv gets the cached inverse of a matrix 

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set_matrix <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get_matrix <- function() x
        set_matrixInv <- function(inverse) inv <<- inverse
        get_matrixInv <- function() inv
        list(set_matrix = set_matrix, get_matrix = get_matrix,
             set_matrixInv = set_matrixInv, get_matrixInv = get_matrixInv)
}


## cacheSolve is a function the computes the inverse of the "matrix" generated by the makeCacheMatrix function above.
## This function checks if the inverse has already been calculated, then it retrieves the inverse from the cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$get_matrixInv()
        if(!is.null(inv)){
                message("Getting cached data...")
                return(inv)
        }
        mat <- x$get_matrix()
        inv <- solve(mat, ...)
        x$set_matrixInv(inv)
        inv
}
